@CareerIntelligencePlatform.Api_HostAddress = http://localhost:5052

### Create Job

POST {{CareerIntelligencePlatform.Api_HostAddress}}/api/jobs
Content-Type: application/json

{
  "title": "Senior Frontend Developer",
  "description": "Frontend development using React and MUI.",
  "salary": {
    "amount": 9000000,
    "currency": "COP"
  }
}

### 
GET {{CareerIntelligencePlatform.Api_HostAddress}}/api/jobs/4100e9b7-e568-4bb6-b0db-cf1c92cea365

### 
GET {{CareerIntelligencePlatform.Api_HostAddress}}/api/jobs/00000000-0000-0000-0000-000000000000

